int _putchar(char c);
void swap_int(int *a, int *b);
int strlen(char *s);
void _puts(char *str);
void print_rev(char *s);
void rev_string (char *s);
void puts2(char *str);
void print_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest *src);
int _atoi(char *s);
